//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSCC360._2.Models
{
    using System;
    
    public enum MemberState : short
    {
        Pending = 0,
        Approved = 1,
        Expired = 2
    }
}
