//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample_ef.net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Sex { get; set; }
        public string State { get; set; }
    
        public virtual lutBreed Breed { get; set; }
        public virtual Dog Sire { get; set; }
        public virtual Dog Dam { get; set; }
        public virtual Member Member { get; set; }
        public virtual Document Pedigree { get; set; }
    }
}
