//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample_ef.net
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mdlGSSCC360Container : DbContext
    {
        public mdlGSSCC360Container()
            : base("name=mdlGSSCC360Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Dog> Dogs { get; set; }
        public virtual DbSet<lutBreed> lutBreeds { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<TrialEntry> TrialEntries { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
    }
}
