//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample_ef.net
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrialEntry
    {
        public int Id { get; set; }
        public string ScoreA { get; set; }
        public string ScoreB { get; set; }
        public int TrialEventId { get; set; }
        public string State { get; set; }
    
        public virtual Dog Dog { get; set; }
        public virtual Member Handler { get; set; }
        public virtual TrialEvent TrialEvent { get; set; }
    }
}
