//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSCC360._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSSCC360_devEntities : DbContext
    {
        public GSSCC360_devEntities()
            : base("name=GSSCC360_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Dog> Dogs { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Events_TrialEvent> Events_TrialEvent { get; set; }
        public virtual DbSet<lutBreed> lutBreeds { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<TrialEntry> TrialEntries { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
    }
}
