//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSCC360._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notification()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Club_Id { get; set; }
        public Nullable<int> TrialEntry_Id { get; set; }
        public Nullable<int> TrialEvent_Id { get; set; }
        public Nullable<int> Dog_Id { get; set; }
    
        public virtual Club Club { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Dog Dog { get; set; }
        public virtual Events_TrialEvent Events_TrialEvent { get; set; }
        public virtual Person Person { get; set; }
        public virtual TrialEntry TrialEntry { get; set; }
    }
}
