//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSCC360._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrialEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrialEntry()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public string ScoreA { get; set; }
        public string ScoreB { get; set; }
        public int TrialEventId { get; set; }
        public TrialEntryState State { get; set; }
        public int Dog_Id { get; set; }
        public int Handler_Id { get; set; }
    
        public virtual Dog Dog { get; set; }
        public virtual Events_TrialEvent Events_TrialEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Member People_Member { get; set; }
    }
}
